spring.application.name=uninoxus_uninoxus
server.port=8081
# Configuracoes de Conexao com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/uninoxus
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truegit reset --soft HEAD~1